sudo: false
language: php
matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: COVERAGE=1
    - php: 7.1
    - php: 7.2
  allow_failures:
    - php: nightly
branches:
  except:
    - /^dist/
    - /^release/
before_script:
  - ./scripts/travis/setup.sh
  - php -i
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - ./scripts/travis/uploadCodeCoverage.sh