sudo: false
language: php
matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COVERAGE=1
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php:  5.3.3
      dist: precise
  allow_failures:
    - php: nightly
    - php:  5.3.3
      dist: precise
branches:
  except:
    - /^dist/
    - /^release/
before_script:
  - ./scripts/travis/setup.sh
  - php -i
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - ./scripts/travis/uploadCodeCoverage.sh